### ISSUE TITLE
Sort doesn't work correct

### ISSUE THREAD

**Issue by pschoenmakers** [baaastijn/ovh_pricelist#2]
Sort on RAM and Private Network both don't sort as expected. 

RAM sort low to high does give this order:
8 GB
64 GB
512 GB
384 GB
32 GB
256 GB
16 GB
128 GB

Private Network does also incorrectly list 3 Gbps between 10 Gbps and 40 Gpbs

**Comment by baaastijn** [comment]
Hello, with the release 2 I fixed the issue. you can now sort RAM size correctly.
