### ISSUE TITLE
Question about JSON

### ISSUE THREAD

**Issue by hvisage** [baaastijn/ovh_pricelist#4]
Good day,

 I'm busy with some PostgreSQL (14) jsonb import and querying (will share the structures etc. at https://gitlab.com/hvisage-pub-stuff/ovh-stuff once "done") , and questions starts popping up:

1. What is the difference between `.plans[].plancode` and `.plans[].product` ? they seem to be always the same?

**Comment by baaastijn** [comment]
Yes, they are the same
But afaik Plancode is filled with billing info, as a commercial array,
where Product is filled With tech specs : CPU, ram, ...

**Comment by hvisage** [comment]
I see now it do make a difference when you get to the `.addon[].planCode` that is the link from the server's `.plan` where the pricing differs for the plans/server, that then have a "generic" `.addon[].product` that links to  `.products[].name` where you get the tech specifications of the "generic" products !

Example with RAM, the one is the extra RAM and the other is when the RAM is "default/standard" (-inc)

```
{
  "product": "ram-64g-ecc-3200",
  "planCode": "ram-64g-adv-gen2",
  "invoiceName": "64GB DDR4 ECC"
}
{
  "product": "ram-64g-ecc-3200",
  "planCode": "ram-64g-adv-gen2-inc",
  "invoiceName": "64GB DDR4 ECC"
}
```
